export const Paths = {
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  VERIFY_OTP: "verify-otp",
  RESET_PASSWORD: "/reset-password",
  ADMIN_PROFILE: "/admin-profile",
  CHANGE_PASSWORD: "/change-password",
  EDIT_PROFILE: "/admin-profile/edit-profile",
  DASHBOARD: "dashboard",
  USER_MANAGEMENT: "/user-management",
  USER_DETAILS: "/user-management/details",
  ADD_USER: "/user-management/add",
  EDIT_USER: "/user-management/edit",
  MEDICINE: "medicine",
  CUSTOMER_MANAGEMENT: "/customer-management",
  CUSTOMER_DETAILS: "/customer-management/details",
  CMS: "cms",
  ROLES: "/roles",
  ROLE_DETAILS: "/roles/details",
  ADD_ROLE: "/roles/add",
  EDIT_ROLE: "/roles/edit",
};
